### ISSUE TITLE
Update for 1.20.6

### ISSUE THREAD

**Issue by 6unsatiable** [Gitko01/Hullabaloo#3]
Could you update the mod for 1.20.6 I really would like to use it on my server

**Comment by ChacePratt** [comment]
Of course - I’ll update it soon

**Comment by ChacePratt** [comment]
Currently, I have finished 99% of the port to 1.20.6, but I'm stuck on one issue with the property delegate of the Mob Attractor. I will be busy the next two weeks so I will not be able to fix that issue until then.

**Comment by 6unsatiable** [comment]
Sounds good! Thank you for porting it! Take your time 😀 while you're busy I will see if I can manage to fix the property delegate issue, haven't made a Minecraft mod since 1.7.10 but I can try lol

**Comment by ChacePratt** [comment]
Turns out the values of property delegates are just limited to the size of 16-bit signed integers now, so I made some custom packets to handle displaying the energy amount on the Mob Attractor GUI.
